TRANSPONDER_COSTS = [1, 5, 15]
TRANSPONDER_CAPACITIES = [10, 40, 100]
FIBER_CAPACITY = 8
POPULATION_SIZE = 10
ITERATIONS = 80
MUTATION_PROBABILITY = 0.005

# Punshiment factors for calculating fitness value
OVERFILLED_FIBER_PUNISHMENT_FACTOR = 200
UNFULFILLED_DEMAND_PUNISHMENT_FACTOR = 3

CROSSOVER_SPLIT_POINTS_NUMBER = 2