TRANSPONDER_COSTS = [1, 5, 15]
TRANSPONDER_CAPACITIES = [10, 40, 100]
FIBER_CAPACITY = 32
POPULATION_SIZE = 10
ITERATIONS = 80
MUTATION_PROBABILITY = 0.005
HARD_ITERATION_LIMIT = 100
NOT_IMPROVING_ITERATION_LIMIT = 120
IMPROVEMENT_THRESHOLD = 0.01

# Punishment factors for calculating fitness value
OVERFILLED_FIBER_PUNISHMENT_FACTOR = 10000
UNFULFILLED_DEMAND_PUNISHMENT_FACTOR = 1000

CROSSOVER_SPLIT_POINTS_NUMBER = 2